export enum OperationType {
  MANDATORY_CONTRIBUTION = 'MANDATORY_CONTRIBUTION',
  STOCK_FEE = 'STOCK_FEE',
  LOAN_PAYMENT = 'LOAN_PAYMENT',
  FEE = 'FEE',
  STOCK_PURCHASE = 'STOCK_PURCHASE',
  LOAN_DISBURSEMENT = 'LOAN_DISBURSEMENT',
  MONTHLY_PAYMENT = 'MONTHLY_PAYMENT',
  ASSET_REVALUATION = 'ASSET_REVALUATION',
  UNDEFINED = 'UNDEFINED',
  STOCK_WITHDRAWAL = 'STOCK_WITHDRAWAL',
  OTHER_WITHDRAWAL = 'OTHER_WITHDRAWAL',
  DIVIDEND_PAYMENT = 'DIVIDEND_PAYMENT',
}
